Added demand of 100% test coverage

diff --git a/.github/workflows/dotnetCourseTemplateTests.yml b/.github/workflows/dotnetCourseTemplateTests.yml
--- a/.github/workflows/dotnetCourseTemplateTests.yml
+++ b/.github/workflows/dotnetCourseTemplateTests.yml
@@ -28,11 +28,29 @@ jobs:
 
     - name: Build CourseTemplate
       run: dotnet build ./CourseTemplate/CourseTemplate.sln --no-restore
+     
+      # Calculate code coverage percentage for unit tests
+    - name: Calculate unit test coverage
+      run: |
+        dotnet test ./CourseTemplate/CourseTemplate.UnitTests/CourseTemplate.UnitTests.csproj --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
 
-    # Run unit tests
-    - name: Run unit tests
-      run: dotnet test ./CourseTemplate/CourseTemplate.UnitTests/CourseTemplate.UnitTests.csproj --no-build --verbosity normal
+        coverage_percentage_unit=$(bash <(curl -s https://codecov.io/bash) -f ./CourseTemplate/CourseTemplate.UnitTests/coverage.opencover.xml -X gcov)
 
-    # Run integration tests
-    - name: Run integration tests
-      run: dotnet test ./CourseTemplate/CourseTemplate.IntegrationTests/CourseTemplate.IntegrationTests.csproj --no-build --verbosity normal
+        if [ "$coverage_percentage_unit" -ne 100 ]; then
+          echo "Error: Code coverage for unit tests is not 100%."
+          exit 1
+        fi
+      shell: bash
+      
+      # Calculate code coverage percentage for integration tests
+    - name: Calculate integration test coverage
+      run: |
+        dotnet test ./CourseTemplate/CourseTemplate.IntegrationTests/CourseTemplate.IntegrationTests.csproj --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
+
+        coverage_percentage_integration=$(bash <(curl -s https://codecov.io/bash) -f ./CourseTemplate/CourseTemplate.IntegrationTests/coverage.opencover.xml -X gcov)
+
+        if [ "$coverage_percentage_integration" -ne 100 ]; then
+          echo "Error: Code coverage for integration tests is not 100%."
+          exit 1
+        fi
+      shell: bash
diff --git a/.github/workflows/dotnetIdentityTests.yml b/.github/workflows/dotnetIdentityTests.yml
--- a/.github/workflows/dotnetIdentityTests.yml
+++ b/.github/workflows/dotnetIdentityTests.yml
@@ -23,10 +23,29 @@ jobs:
     - name: Build
       run: dotnet build ./Identity/Identity.sln --no-restore
 
-    # Run unit tests
-    - name: Run unit tests
-      run: dotnet test ./Identity/Identity.UnitTests/Identity.UnitTests.csproj --no-build --verbosity normal
+    # Calculate code coverage percentage for unit tests
 
-    # Run integration tests
-    - name: Run integration tests
-      run: dotnet test ./Identity/Identity.IntegrationTests/Identity.IntegrationTests.csproj --no-build --verbosity normal
+    - name: Calculate unit test coverage
+      run: |
+        dotnet test ./Identity/Identity.UnitTests/Identity.UnitTests.csproj --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
+
+        coverage_percentage_unit=$(bash <(curl -s https://codecov.io/bash) -f ./Identity/Identity.UnitTests/coverage.opencover.xml -X gcov)
+
+        if [ "$coverage_percentage_unit" -ne 100 ]; then
+          echo "Error: Code coverage for unit tests is not 100%."
+          exit 1
+        fi
+      shell: bash
+      
+      # Calculate code coverage percentage for integration tests
+    - name: Calculate integration test coverage
+      run: |
+        dotnet test ./Identity/Identity.IntegrationTests/Identity.IntegrationTests.csproj --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
+
+        coverage_percentage_integration=$(bash <(curl -s https://codecov.io/bash) -f ./Identity/Identity.IntegrationTests/coverage.opencover.xml -X gcov)
+
+        if [ "$coverage_percentage_integration" -ne 100 ]; then
+          echo "Error: Code coverage for integration tests is not 100%."
+          exit 1
+        fi
+      shell: bash
diff --git a/.github/workflows/dotnetMaterialsTests.yml b/.github/workflows/dotnetMaterialsTests.yml
--- a/.github/workflows/dotnetMaterialsTests.yml
+++ b/.github/workflows/dotnetMaterialsTests.yml
@@ -27,12 +27,31 @@ jobs:
       run: dotnet restore ./Materials/Materials.sln
 
     - name: Build Materials
-      run: dotnet build ./Materials/Materials.sln --no-restore
+      run: dotnet build ./Materials/Materials.sln --no-restore  
+      
+    # Calculate code coverage percentage for unit tests
 
-    # Run unit tests
-    - name: Run unit tests
-      run: dotnet test ./Materials/Materials.UnitTests/Materials.UnitTests.csproj --no-build --verbosity normal
+    - name: Calculate unit test coverage
+      run: |
+        dotnet test ./Materials/Materials.UnitTests/Materials.UnitTests.csproj --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
 
-    # Run integration tests
-    - name: Run integration tests
-      run: dotnet test ./Materials/Materials.IntegrationTests/Materials.IntegrationTests.csproj --no-build --verbosity normal
+        coverage_percentage_unit=$(bash <(curl -s https://codecov.io/bash) -f ./Materials/Materials.UnitTests/coverage.opencover.xml -X gcov)
+
+        if [ "$coverage_percentage_unit" -ne 100 ]; then
+          echo "Error: Code coverage for unit tests is not 100%."
+          exit 1
+        fi
+      shell: bash
+      
+      # Calculate code coverage percentage for integration tests
+    - name: Calculate integration test coverage
+      run: |
+        dotnet test ./Materials/Materials.IntegrationTests/Materials.IntegrationTests.csproj --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
+
+        coverage_percentage_integration=$(bash <(curl -s https://codecov.io/bash) -f ./Materials/Materials.IntegrationTests/coverage.opencover.xml -X gcov)
+
+        if [ "$coverage_percentage_integration" -ne 100 ]; then
+          echo "Error: Code coverage for integration tests is not 100%."
+          exit 1
+        fi
+      shell: bash
